### ISSUE TITLE
Error 1051 when creating a class with a name that already exists in memory

### ISSUE THREAD

**Issue by tholsan** [weaddquality/gsharp#3]
Right-click>Create Class. Name it to a name of a class that already exists. The "Create Class" will be greyed out, but at this point, change the template type (to native e.g.), and then just add a character to the name and delete it again, and the "Create Class" is no longer greyed out. Click "Create Class", then this error appears:

![skarmklipp 2018-10-09 13 56 21](https://user-images.githubusercontent.com/3741696/46667903-4a4a8f00-cbcb-11e8-9086-fdc8a2bc7b7a.png)

**Comment by NiUseGit** [comment]
Fixed, will be released in next LV2020-3 version.
